import fs from 'fs';
import path from 'path';

const games = [
  // Launchers & Clients
  ["Steam", "steam.exe", "Valve Steam Client"],
  ["Steam Service", "steamservice.exe", "Valve Steam Service"],
  ["Steam Web Helper", "steamwebhelper.exe", "Steam Embedded Browser"],
  ["Epic Games Launcher", "epicgameslauncher.exe", "Epic Games Store & Launcher"],
  ["Unreal Engine Launcher", "unrealengine.exe", "Unreal Engine Launcher"],
  ["Riot Client", "riotclientservices.exe", "Riot Games Client Launcher"],
  ["Riot Vanguard", "vgtray.exe", "Riot Vanguard Anti-Cheat Tray"],
  ["Battle.net", "battle.net.exe", "Blizzard Battle.net Desktop App"],
  ["Battle.net Agent", "agent.exe", "Blizzard Battle.net Agent"],
  ["EA Desktop", "eadesktop.exe", "Electronic Arts Desktop Client"],
  ["EA Background Service", "eabackgroundservice.exe", "EA App Background Service"],
  ["Origin", "origin.exe", "EA Origin Client"],
  ["Origin Web Helper", "originwebhelperservice.exe", "Origin Helper"],
  ["Ubisoft Connect", "ubisoftconnect.exe", "Ubisoft Game Client"],
  ["Uplay", "uplay.exe", "Legacy Ubisoft Uplay"],
  ["GOG Galaxy", "gog galaxy.exe", "GOG Galaxy Client"],
  ["GOG Galaxy Communication", "galaxycommunication.exe", "GOG Galaxy Service"],
  ["Rockstar Games Launcher", "launcher.exe", "Rockstar Games Launcher"],
  ["Rockstar Games Service", "rockstarservice.exe", "Rockstar Games Service"],
  ["Bethesda.net Launcher", "bethesdanetlauncher.exe", "Bethesda Game Launcher"],
  ["Itch.io", "itch.exe", "Itch.io Indie Game Client"],
  ["Playnite", "playnite.desktopapp.exe", "Playnite Video Game Library"],
  ["Playnite Fullscreen", "playnite.fullscreenapp.exe", "Playnite Game Launcher"],
  ["Heroic Games Launcher", "heroic.exe", "Heroic Open Source Games Launcher"],
  ["Amazon Games", "amazongames.exe", "Amazon Games App"],
  ["TLauncher", "tlauncher.exe", "Minecraft TLauncher"],
  ["Lunar Client", "lunar client.exe", "Minecraft Lunar Client"],
  ["Badlion Client", "badlion client.exe", "Minecraft Badlion Client"],
  ["Feather Launcher", "feather launcher.exe", "Minecraft Feather Client"],
  ["Prism Launcher", "prismlauncher.exe", "Minecraft Prism Launcher"],
  ["ATLauncher", "atlauncher.exe", "Minecraft ATLauncher"],
  ["GDLauncher", "gdlauncher.exe", "Minecraft GDLauncher"],
  ["Overwolf", "overwolf.exe", "Overwolf Gaming Overlay & Apps"],
  ["CurseForge", "curseforge.exe", "CurseForge Mod & Addon Manager"],

  // Major Esports & Multiplayer
  ["League of Legends", "leagueclient.exe", "Riot Games League of Legends Client"],
  ["League of Legends Game", "league of legends.exe", "League of Legends In-Game Engine"],
  ["Valorant", "valorant.exe", "Riot Games Valorant"],
  ["Valorant Shipping", "valorant-win64-shipping.exe", "Valorant Game Binary"],
  ["Counter-Strike 2", "cs2.exe", "Counter-Strike 2"],
  ["Counter-Strike Global Offensive", "csgo.exe", "CS:GO Legacy"],
  ["Dota 2", "dota2.exe", "Valve Dota 2"],
  ["Fortnite Launcher", "fortnitelauncher.exe", "Fortnite Launcher"],
  ["Fortnite Client", "fortniteclient-win64-shipping.exe", "Fortnite Battle Royale Engine"],
  ["Apex Legends", "r5apex.exe", "EA Respawn Apex Legends"],
  ["Apex Legends Steam", "r5apex_dx12.exe", "Apex Legends DX12 Engine"],
  ["PUBG Battlegrounds", "tslgame.exe", "PUBG Battlegrounds Engine"],
  ["Rainbow Six Siege", "rainbowsix.exe", "Ubisoft Tom Clancy's Rainbow Six Siege"],
  ["Rainbow Six Siege Vulkan", "rainbowsix_vulkan.exe", "Rainbow Six Siege Vulkan Engine"],
  ["Overwatch", "overwatch.exe", "Blizzard Overwatch 2"],
  ["Rocket League", "rocketleague.exe", "Psyonix Rocket League"],
  ["Dead by Daylight", "deadbydaylight-win64-shipping.exe", "Dead by Daylight"],
  ["Rust", "rustclient.exe", "Facepunch Rust"],
  ["ARK Survival Evolved", "shootergame.exe", "ARK Survival Evolved Engine"],
  ["ARK Survival Ascended", "arkascended.exe", "ARK Survival Ascended"],
  ["Warframe", "warframe.x64.exe", "Digital Extremes Warframe"],
  ["Destiny 2", "destiny2.exe", "Bungie Destiny 2"],
  ["World of Warcraft", "wow.exe", "Blizzard World of Warcraft"],
  ["World of Warcraft Classic", "wowclassic.exe", "World of Warcraft Classic"],
  ["Final Fantasy XIV", "ffxiv_dx11.exe", "Square Enix Final Fantasy XIV"],
  ["RuneScape", "runescape.exe", "Jagex RuneScape Desktop Client"],
  ["Old School RuneScape", "osclient.exe", "Old School RuneScape Client"],
  ["RuneLite", "runelite.exe", "Old School RuneScape RuneLite Client"],
  ["Roblox Player", "robloxplayerbeta.exe", "Roblox Game Client"],
  ["Roblox Player Launcher", "robloxplayerlauncher.exe", "Roblox Launcher"],
  ["Roblox Studio", "robloxstudiobeta.exe", "Roblox Development Studio"],
  ["Minecraft", "minecraft.exe", "Mojang Minecraft Launcher"],
  ["Minecraft Bedrock", "minecraft.windows.exe", "Minecraft for Windows UWP"],

  // Gacha & Asian MMORPG / ARPG
  ["Genshin Impact", "genshinimpact.exe", "HoYoverse Genshin Impact"],
  ["Genshin Impact Launcher", "launcher.exe", "HoYoverse Launcher"],
  ["Honkai Star Rail", "starrail.exe", "HoYoverse Honkai: Star Rail"],
  ["Zenless Zone Zero", "zzz.exe", "HoYoverse Zenless Zone Zero"],
  ["Honkai Impact 3rd", "bh3.exe", "HoYoverse Honkai Impact 3rd"],
  ["Wuthering Waves", "wutheringwaves.exe", "Kuro Games Wuthering Waves"],
  ["Tower of Fantasy", "qrsl.exe", "Tower of Fantasy Engine"],
  ["Lost Ark", "lostark.exe", "Smilegate Lost Ark"],
  ["Black Desert Online", "blackdesert64.exe", "Pearl Abyss Black Desert Online"],
  ["MapleStory", "maplestory.exe", "Nexon MapleStory"],
  ["Guild Wars 2", "gw2-64.exe", "ArenaNet Guild Wars 2"],
  ["The Elder Scrolls Online", "eso64.exe", "Zenimax The Elder Scrolls Online"],

  // Singleplayer & RPG Blockbusters
  ["Grand Theft Auto V", "gta5.exe", "Rockstar Grand Theft Auto V"],
  ["GTA V Enhanced", "playgtav.exe", "Rockstar GTA V Launcher"],
  ["Red Dead Redemption 2", "rdr2.exe", "Rockstar Red Dead Redemption 2"],
  ["Grand Theft Auto San Andreas", "gta_sa.exe", "GTA San Andreas"],
  ["Grand Theft Auto Vice City", "gta_vc.exe", "GTA Vice City"],
  ["Grand Theft Auto III", "gta3.exe", "GTA III"],
  ["Cyberpunk 2077", "cyberpunk2077.exe", "CD Projekt Red Cyberpunk 2077"],
  ["The Witcher 3", "witcher3.exe", "CD Projekt Red The Witcher 3: Wild Hunt"],
  ["Elden Ring", "eldenring.exe", "FromSoftware Elden Ring"],
  ["Dark Souls Remastered", "darksoulsremastered.exe", "FromSoftware Dark Souls"],
  ["Dark Souls II", "darksoulsii.exe", "FromSoftware Dark Souls II"],
  ["Dark Souls III", "darksoulsiii.exe", "FromSoftware Dark Souls III"],
  ["Sekiro Shadows Die Twice", "sekiro.exe", "FromSoftware Sekiro"],
  ["Armored Core VI", "armoredcore6.exe", "FromSoftware Armored Core VI"],
  ["Monster Hunter World", "monsterhunterworld.exe", "Capcom Monster Hunter: World"],
  ["Monster Hunter Rise", "monsterhunterrise.exe", "Capcom Monster Hunter Rise"],
  ["Monster Hunter Wilds", "monsterhunterwilds.exe", "Capcom Monster Hunter Wilds"],
  ["Baldur's Gate 3", "bg3.exe", "Larian Studios Baldur's Gate 3"],
  ["Baldur's Gate 3 DX11", "bg3_dx11.exe", "Baldur's Gate 3 DirectX 11"],
  ["Diablo IV", "diablo iv.exe", "Blizzard Diablo IV"],
  ["Diablo III", "diablo iii64.exe", "Blizzard Diablo III"],
  ["Diablo II Resurrected", "d2r.exe", "Blizzard Diablo II Resurrected"],
  ["Starfield", "starfield.exe", "Bethesda Starfield"],
  ["Skyrim Special Edition", "skyrimse.exe", "Bethesda The Elder Scrolls V: Skyrim"],
  ["Fallout 4", "fallout4.exe", "Bethesda Fallout 4"],
  ["Fallout 76", "fallout76.exe", "Bethesda Fallout 76"],
  ["Palworld", "palworld-win64-shipping.exe", "Pocketpair Palworld"],
  ["Helldivers 2", "helldivers2.exe", "Arrowhead Helldivers 2"],
  ["Lethal Company", "lethal company.exe", "Zeekerss Lethal Company"],
  ["Phasmophobia", "phasmophobia.exe", "Kinetic Games Phasmophobia"],
  ["Among Us", "among us.exe", "Innersloth Among Us"],
  ["Fall Guys", "fallguys_client.exe", "Epic Games Fall Guys"],
  ["Terraria", "terraria.exe", "Re-Logic Terraria"],
  ["Stardew Valley", "stardew valley.exe", "ConcernedApe Stardew Valley"],
  ["The Sims 4", "ts4_x64.exe", "EA The Sims 4"],
  ["The Sims 3", "ts3.exe", "EA The Sims 3"],
  ["Hogwarts Legacy", "hogwartslegacy.exe", "Warner Bros Hogwarts Legacy"],
  ["God of War", "gow.exe", "Sony PlayStation God of War"],
  ["God of War Ragnarok", "gowragnarok.exe", "Sony God of War Ragnarok"],
  ["Marvel's Spider-Man Remastered", "spider-man.exe", "Insomniac Marvel's Spider-Man"],
  ["Marvel's Spider-Man Miles Morales", "milesmorales.exe", "Spider-Man: Miles Morales"],
  ["The Last of Us Part I", "tlou-i.exe", "Naughty Dog The Last of Us"],
  ["Horizon Zero Dawn", "horizonzerodawn.exe", "Guerrilla Horizon Zero Dawn"],
  ["Horizon Forbidden West", "horizonforbiddenwest.exe", "Horizon Forbidden West"],
  ["Ghost of Tsushima", "ghostoftsushima.exe", "Sucker Punch Ghost of Tsushima"],
  ["Death Stranding", "ds.exe", "Kojima Productions Death Stranding"],
  ["Resident Evil 4 Remake", "re4.exe", "Capcom Resident Evil 4"],
  ["Resident Evil Village", "re8.exe", "Capcom Resident Evil Village"],
  ["Resident Evil 2 Remake", "re2.exe", "Capcom Resident Evil 2"],
  ["Resident Evil 3 Remake", "re3.exe", "Capcom Resident Evil 3"],
  ["Silent Hill 2 Remake", "sh2.exe", "Konami Silent Hill 2"],
  ["Dead Space Remake", "deadspace.exe", "EA Dead Space Remake"],
  ["Call of Duty Modern Warfare", "cod.exe", "Activision Call of Duty HQ"],
  ["Call of Duty Warzone", "warzone.exe", "Call of Duty: Warzone"],
  ["Call of Duty Black Ops 6", "blackops6.exe", "Call of Duty: Black Ops 6"],
  ["Battlefield 2042", "bf2042.exe", "EA DICE Battlefield 2042"],
  ["Battlefield V", "bfv.exe", "EA DICE Battlefield V"],
  ["Battlefield 1", "bf1.exe", "EA DICE Battlefield 1"],
  ["Halo Infinite", "haloinfinite.exe", "Xbox Game Studios Halo Infinite"],
  ["Halo Master Chief Collection", "mcclauncher.exe", "Halo: Master Chief Collection"],
  ["Doom Eternal", "doometernalx64vk.exe", "id Software Doom Eternal"],
  ["Doom 2016", "doomx64.exe", "id Software Doom"],
  ["Wolfenstein II", "new_colossus_x64tk.exe", "MachineGames Wolfenstein II"],
  ["Payday 2", "payday2_win32_release.exe", "Starbreeze Payday 2"],
  ["Payday 3", "payday3client-win64-shipping.exe", "Starbreeze Payday 3"],
  ["Deep Rock Galactic", "fsd-win64-shipping.exe", "Ghost Ship Deep Rock Galactic"],
  ["Sea of Thieves", "sotgame.exe", "Rare Sea of Thieves"],
  ["No Man's Sky", "nms.exe", "Hello Games No Man's Sky"],
  ["Subnautica", "subnautica.exe", "Unknown Worlds Subnautica"],
  ["Subnautica Below Zero", "subnauticabelowzero.exe", "Subnautica: Below Zero"],
  ["Raft", "raft.exe", "Redbeet Raft"],
  ["The Forest", "theforest.exe", "Endnight The Forest"],
  ["Sons of the Forest", "sonsoftheforest.exe", "Endnight Sons of the Forest"],
  ["Green Hell", "gh.exe", "Creepy Jar Green Hell"],
  ["Valheim", "valheim.exe", "Iron Gate Valheim"],
  ["Enshrouded", "enshrouded.exe", "Keen Games Enshrouded"],
  ["V Rising", "v rising.exe", "Stunlock V Rising"],
  ["Hollow Knight", "hollow_knight.exe", "Team Cherry Hollow Knight"],
  ["Hades", "hades.exe", "Supergiant Games Hades"],
  ["Hades II", "hades2.exe", "Supergiant Games Hades II"],
  ["Dead Cells", "deadcells.exe", "Motion Twin Dead Cells"],
  ["The Binding of Isaac Rebirth", "isaac-ng.exe", "The Binding of Isaac: Rebirth"],
  ["Enter the Gungeon", "etg.exe", "Dodge Roll Enter the Gungeon"],
  ["Risk of Rain 2", "risk of rain 2.exe", "Hopoo Risk of Rain 2"],
  ["Vampire Survivors", "vampire survivors.exe", "Poncle Vampire Survivors"],
  ["Brotato", "brotato.exe", "Blobfish Brotato"],
  ["Slay the Spire", "slaythespire.exe", "Mega Crit Slay the Spire"],
  ["Balatro", "balatro.exe", "LocalThunk Balatro Poker Roguelike"],
  ["Celeste", "celeste.exe", "Maddy Makes Games Celeste"],
  ["Cuphead", "cuphead.exe", "Studio MDHR Cuphead"],
  ["Ori and the Blind Forest", "ori.exe", "Moon Studios Ori and the Blind Forest"],
  ["Ori and the Will of the Wisps", "oriandthewillofthewisps.exe", "Ori and the Will of the Wisps"],
  ["Geometry Dash", "geometrydash.exe", "RobTop Geometry Dash"],
  ["Osu!", "osu!.exe", "peppy osu! rhythm game"],
  ["Clone Hero", "clonehero.exe", "Clone Hero Guitar Rhythm"],
  ["A Dance of Fire and Ice", "adofai.exe", "A Dance of Fire and Ice"],
  ["Muse Dash", "musedash.exe", "PeroPeroGames Muse Dash"],
  ["Beat Saber PC", "beatsaber.exe", "Beat Games Beat Saber"],
  ["VRChat", "vrchat.exe", "VRChat Social VR World"],

  // Sports & Racing
  ["EA Sports FC 25", "fc25.exe", "EA Sports FC 25 Football"],
  ["EA Sports FC 24", "fc24.exe", "EA Sports FC 24 Football"],
  ["FIFA 23", "fifa23.exe", "EA Sports FIFA 23"],
  ["FIFA 22", "fifa22.exe", "EA Sports FIFA 22"],
  ["FIFA 21", "fifa21.exe", "EA Sports FIFA 21"],
  ["eFootball", "efootball.exe", "Konami eFootball PES"],
  ["NBA 2K25", "nba2k25.exe", "2K Games NBA 2K25"],
  ["NBA 2K24", "nba2k24.exe", "2K Games NBA 2K24"],
  ["NBA 2K23", "nba2k23.exe", "2K Games NBA 2K23"],
  ["WWE 2K24", "wwe2k24.exe", "2K Games WWE 2K24"],
  ["Madden NFL 25", "madden25.exe", "EA Sports Madden NFL 25"],
  ["Forza Horizon 5", "forzahorizon5.exe", "Playground Games Forza Horizon 5"],
  ["Forza Horizon 4", "forzahorizon4.exe", "Playground Games Forza Horizon 4"],
  ["Forza Motorsport", "forzamotorsport.exe", "Turn 10 Forza Motorsport"],
  ["F1 24", "f1_24.exe", "EA Sports F1 24 Racing"],
  ["F1 23", "f1_23.exe", "EA Sports F1 23 Racing"],
  ["Assetto Corsa", "acs.exe", "Kunos Assetto Corsa Racing"],
  ["Assetto Corsa Competizione", "acc.exe", "Assetto Corsa Competizione"],
  ["iRacing", "iracingsim64dx11.exe", "iRacing Motorsport Simulation"],
  ["BeamNG.drive", "beamng.drive.x64.exe", "BeamNG Vehicle Physics Simulation"],
  ["Need for Speed Unbound", "nfsunbound.exe", "EA Need for Speed Unbound"],
  ["Need for Speed Heat", "nfsheat.exe", "EA Need for Speed Heat"],
  ["Euro Truck Simulator 2", "eurotrucks2.exe", "SCS Euro Truck Simulator 2"],
  ["American Truck Simulator", "amtrucks.exe", "SCS American Truck Simulator"],
  ["CarX Drift Racing Online", "carx_drift_racing_online.exe", "CarX Technologies"],
  ["Trackmania", "trackmania.exe", "Ubisoft Nadeo Trackmania"],

  // Strategy, City Building & Sandbox
  ["Civilization VI", "civilizationvi.exe", "Firaxis Sid Meier's Civilization VI"],
  ["Civilization V", "civilizationv.exe", "Civilization V"],
  ["Civilization VII", "civilizationvii.exe", "Civilization VII"],
  ["Crusader Kings III", "ck3.exe", "Paradox Crusader Kings III"],
  ["Hearts of Iron IV", "hoi4.exe", "Paradox Hearts of Iron IV"],
  ["Europa Universalis IV", "eu4.exe", "Paradox Europa Universalis IV"],
  ["Stellaris", "stellaris.exe", "Paradox Stellaris Sci-Fi 4X"],
  ["Victoria 3", "victoria3.exe", "Paradox Victoria 3"],
  ["Age of Empires IV", "relliccardinal.exe", "Age of Empires IV"],
  ["Age of Empires II Definitive Edition", "aoe2de.exe", "Age of Empires II: DE"],
  ["StarCraft II", "sc2_x64.exe", "Blizzard StarCraft II"],
  ["Total War Warhammer III", "warhammer3.exe", "Creative Assembly Total War"],
  ["Total War Three Kingdoms", "three_kingdoms.exe", "Total War: Three Kingdoms"],
  ["Total War Rome II", "rome2.exe", "Total War: Rome II"],
  ["Cities Skylines", "cities.exe", "Colossal Order Cities: Skylines"],
  ["Cities Skylines II", "cities2.exe", "Cities: Skylines II"],
  ["Manor Lords", "manorlords-win64-shipping.exe", "Slavic Magic Manor Lords"],
  ["Frostpunk", "frostpunk.exe", "11 bit studios Frostpunk"],
  ["Frostpunk 2", "frostpunk2.exe", "11 bit studios Frostpunk 2"],
  ["RimWorld", "rimworldwin64.exe", "Ludeon Studios RimWorld"],
  ["Factorio", "factorio.exe", "Wube Software Factorio"],
  ["Satisfactory", "factorygame-win64-shipping.exe", "Coffee Stain Satisfactory"],
  ["Dyson Sphere Program", "dsp.exe", "Youthcat Dyson Sphere Program"],
  ["Oxygen Not Included", "oxygennotincluded.exe", "Klei Oxygen Not Included"],
  ["Football Manager 2024", "fm.exe", "Sports Interactive Football Manager 2024"],
  ["Football Manager 2023", "fm23.exe", "Football Manager 2023"],
  ["Kerbal Space Program", "ksp_x64.exe", "Squad Kerbal Space Program"],
  ["Kerbal Space Program 2", "ksp2_x64.exe", "Kerbal Space Program 2"],
  ["Microsoft Flight Simulator", "flightsimulator.exe", "Microsoft Flight Simulator"],
  ["X-Plane 12", "x-plane.exe", "Laminar Research X-Plane 12"],

  // Emulators
  ["RPCS3 PS3 Emulator", "rpcs3.exe", "PlayStation 3 Emulator"],
  ["PCSX2 PS2 Emulator", "pcsx2-qt.exe", "PlayStation 2 QT Emulator"],
  ["PCSX2 Legacy", "pcsx2.exe", "PlayStation 2 Emulator"],
  ["Dolphin GameCube/Wii Emulator", "dolphin.exe", "Nintendo GameCube & Wii Emulator"],
  ["Yuzu Nintendo Switch Emulator", "yuzu.exe", "Nintendo Switch Emulator"],
  ["Ryujinx Nintendo Switch Emulator", "ryujinx.exe", "Nintendo Switch Emulator"],
  ["Cemu Wii U Emulator", "cemu.exe", "Nintendo Wii U Emulator"],
  ["Citra Nintendo 3DS Emulator", "citra-qt.exe", "Nintendo 3DS Emulator"],
  ["DuckStation PS1 Emulator", "duckstation-qt-x64-releaseltcg.exe", "PlayStation 1 Emulator"],
  ["PPSSPP PSP Emulator", "ppssppwindows64.exe", "Sony PSP Emulator"],
  ["RetroArch", "retroarch.exe", "Multi-system Retro Gaming Frontend"],
  ["VBA-M Game Boy Advance Emulator", "visualboyadvance-m.exe", "GBA Emulator"],
  ["DeSmuME Nintendo DS Emulator", "desmume.exe", "Nintendo DS Emulator"],
  ["melonDS Nintendo DS Emulator", "melonds.exe", "Nintendo DS Emulator"],
  ["mGBA Game Boy Advance Emulator", "mgba.exe", "Game Boy Advance Emulator"],
  ["FCEUX NES Emulator", "fceux.exe", "Nintendo Entertainment System Emulator"],
  ["Snes9x SNES Emulator", "snes9x-x64.exe", "Super Nintendo Emulator"],
  ["ZSNES", "zsnesw.exe", "Super Nintendo Emulator"],
  ["BlueStacks App Player", "bluestacks.exe", "Android Mobile Game Emulator"],
  ["BlueStacks HD Player", "hd-player.exe", "BlueStacks Core Android Engine"],
  ["BlueStacks Services", "bluestackssvc.exe", "BlueStacks Background Service"],
  ["LDPlayer 9", "dnplayer.exe", "LDPlayer Android Game Emulator"],
  ["LDPlayer Box Head", "ldboxhead.exe", "LDPlayer Virtual Machine"],
  ["NoxPlayer", "nox.exe", "Nox Android Mobile Game Emulator"],
  ["Nox Virtual Machine", "noxvmhandle.exe", "Nox VM Process"],
  ["MEmu Play", "memu.exe", "MEmu Android Gaming Emulator"],
  ["MEmu Console", "memuconsole.exe", "MEmu Virtual Machine Console"],
  ["GameLoop Tencent", "appmarket.exe", "Tencent GameLoop Android Emulator"],
  ["GameLoop UI", "gameloop.exe", "GameLoop Emulator Launcher"],
  ["MuMu Player", "mumuplayer.exe", "NetEase MuMu Android Emulator"],
  ["Genymotion", "genymotion.exe", "Genymotion Android Platform"]
];

const socials = [
  ["WhatsApp Desktop", "whatsapp.exe", "WhatsApp Messaging App"],
  ["WhatsApp Root", "whatsapp.root.exe", "WhatsApp Windows UWP Host"],
  ["WhatsApp Desktop Host", "whatsappdesktop.exe", "WhatsApp Desktop Client"],
  ["WhatsApp Background Host", "whatsapphost.exe", "WhatsApp Background Service"],
  ["Telegram Desktop", "telegram.exe", "Telegram Messenger"],
  ["Telegram Update", "updater.exe", "Telegram Auto Updater"],
  ["TikTok Desktop", "tiktok.exe", "TikTok Short Form Video App"],
  ["Instagram Desktop", "instagram.exe", "Instagram Social App"],
  ["Facebook Messenger", "messenger.exe", "Meta Facebook Messenger"],
  ["Facebook App", "facebook.exe", "Meta Facebook Desktop App"],
  ["Snapchat Desktop", "snapchat.exe", "Snapchat Camera & Chat App"],
  ["Twitter Desktop", "twitter.exe", "Twitter / X Social Network"],
  ["X Desktop App", "x.exe", "X Social Platform App"],
  ["Reddit Desktop App", "reddit.exe", "Reddit Forum & Media App"],
  ["Viber Messenger", "viber.exe", "Rakuten Viber Calls & Chat"],
  ["Skype Desktop", "skype.exe", "Microsoft Skype Communication"],
  ["Skype App UWP", "skypeapp.exe", "Microsoft Skype Store App"],
  ["LINE Messenger", "line.exe", "LINE Instant Messenger"],
  ["WeChat Desktop", "wechat.exe", "Tencent WeChat Messaging"],
  ["WeChat App Service", "wecatapp.exe", "Tencent WeChat Helper"],
  ["Tencent QQ", "qq.exe", "Tencent QQ Chat Platform"],
  ["Tencent TIM", "tim.exe", "Tencent TIM Office Messenger"],
  ["KakaoTalk", "kakaotalk.exe", "KakaoTalk Instant Messenger"],
  ["Signal Desktop", "signal.exe", "Signal Private Messenger"],
  ["Session Messenger", "session.exe", "Session Decentralized Messenger"],
  ["Element Matrix Chat", "element.exe", "Element Matrix Secure Chat"],
  ["Tinder Desktop", "tinder.exe", "Tinder Dating App"],
  ["Bumble Desktop", "bumble.exe", "Bumble Dating App"],
  ["Badoo Desktop", "badoo.exe", "Badoo Social Discovery"],
  ["Threads by Instagram", "threads.exe", "Threads Text Social Network"],
  ["BeReal Desktop", "bereal.exe", "BeReal Photo Sharing"],
  ["Pinterest Desktop", "pinterest.exe", "Pinterest Inspiration Boards"],
  ["Tumblr Desktop", "tumblr.exe", "Tumblr Microblogging Platform"],
  ["Kik Messenger", "kik.exe", "Kik Interactive Messenger"],
  ["ICQ New", "icq.exe", "ICQ Instant Messenger"],
  ["Zalo Desktop", "zalo.exe", "Zalo Vietnamese Messenger"],
  ["VK Messenger", "vk.exe", "VKontakte Social Network App"],
  ["Clubhouse Desktop", "clubhouse.exe", "Clubhouse Drop-in Audio Chat"],
  ["Omegle Desktop App", "omegle.exe", "Omegle Random Video Chat"],
  ["OmeTV Desktop", "ometv.exe", "OmeTV Video Chat Network"],
  ["Chatroulette App", "chatroulette.exe", "Chatroulette Webcam Chat"],
  ["MeetMe Desktop", "meetme.exe", "MeetMe Social Dating App"],
  ["Tagged Desktop", "tagged.exe", "Tagged Social Discovery App"]
];

const streaming = [
  ["Netflix Desktop", "netflix.exe", "Netflix Streaming Movies & TV"],
  ["Spotify Music", "spotify.exe", "Spotify Music & Podcasts Streaming"],
  ["Spotify Web Helper", "spotifywebhelper.exe", "Spotify Background Controller"],
  ["Amazon Prime Video", "primevideo.exe", "Amazon Prime Video Player"],
  ["Disney+ Desktop", "disneyplus.exe", "Disney+ Streaming App"],
  ["Hulu Desktop", "hulu.exe", "Hulu Streaming TV & Movies"],
  ["HBO Max / Max", "max.exe", "Max Streaming Entertainment"],
  ["YouTube Desktop PWA", "youtube.exe", "YouTube Video Streaming App"],
  ["YouTube Music", "youtubemusic.exe", "YouTube Music Desktop Player"],
  ["Twitch Desktop", "twitch.exe", "Twitch Live Gaming Streams"],
  ["Crunchyroll Desktop", "crunchyroll.exe", "Crunchyroll Anime Streaming"],
  ["Apple TV Desktop", "appletv.exe", "Apple TV+ Streaming App"],
  ["Apple Music Desktop", "applemusic.exe", "Apple Music Lossless Player"],
  ["iTunes", "itunes.exe", "Apple iTunes Media & Store"],
  ["Deezer Desktop", "deezer.exe", "Deezer Music Streaming"],
  ["Tidal Music", "tidal.exe", "Tidal Hi-Fi Audio Streaming"],
  ["SoundCloud Desktop", "soundcloud.exe", "SoundCloud Music & Mixes"],
  ["Amazon Music", "amazon music.exe", "Amazon Music Player"],
  ["Pandora Desktop", "pandora.exe", "Pandora Radio Streaming"],
  ["Audacy", "audacy.exe", "Audacy Radio & Podcasts"],
  ["iHeartRadio", "iheartradio.exe", "iHeartRadio Live Stations"],
  ["Stremio Video Hub", "stremio.exe", "Stremio Media & Addon Center"],
  ["Popcorn Time", "popcorn time.exe", "Popcorn Time Torrent Streaming"],
  ["Kodi Home Theater", "kodi.exe", "Kodi Open Source Entertainment Center"],
  ["Plex Media Player", "plexmediaplayer.exe", "Plex Desktop Client Player"],
  ["Plex Desktop", "plex.exe", "Plex Streaming & Server Client"],
  ["Jellyfin Media Player", "jellyfinmediaplayer.exe", "Jellyfin Open Source Media Player"],
  ["Emby Theater", "embytheater.exe", "Emby Media Theater Player"],
  ["PotPlayer", "potplayermini64.exe", "Daum PotPlayer Video Player"],
  ["PotPlayer 32", "potplayermini.exe", "PotPlayer Media Engine"],
  ["KMPlayer", "kmplayer.exe", "Pandora KMPlayer Media Player"],
  ["KMPlayer 64X", "kmplayer64.exe", "KMPlayer 64X High Res Video"],
  ["GOM Player", "gom.exe", "GOM Media Player"],
  ["GOM Player Plus", "gom64.exe", "GOM Player Plus Video Engine"],
  ["VLC Media Player", "vlc.exe", "VideoLAN VLC Media Player"],
  ["Media Player Classic HC", "mpc-hc64.exe", "MPC-HC Video Player"],
  ["Media Player Classic BE", "mpc-be64.exe", "MPC-BE Video Player"],
  ["AIMP Audio Player", "aimp.exe", "AIMP High Quality Audio Player"],
  ["Foobar2000", "foobar2000.exe", "Foobar2000 Advanced Audio Player"],
  ["Winamp Player", "winamp.exe", "Winamp Classic Media Player"],
  ["MusicBee", "musicbee.exe", "MusicBee Music Manager & Player"],
  ["MediaMonkey", "mediamonkey.exe", "MediaMonkey Audio Video Library"],
  ["qBittorrent", "qbittorrent.exe", "qBittorrent P2P Torrent Client"],
  ["uTorrent", "utorrent.exe", "BitTorrent uTorrent Client"],
  ["uTorrent Web", "utorrentweb.exe", "uTorrent Web Downloader"],
  ["BitTorrent Client", "bittorrent.exe", "BitTorrent Official P2P Client"],
  ["BitTorrent Web", "bittorrentweb.exe", "BitTorrent Web Player & Downloader"],
  ["Deluge Torrent", "deluge.exe", "Deluge BitTorrent Client"],
  ["Transmission Torrent", "transmission-qt.exe", "Transmission BitTorrent Client"],
  ["BiglyBT", "biglybt.exe", "BiglyBT Feature Rich Torrent Client"],
  ["Vuze Torrent Client", "vuze.exe", "Vuze Azureus P2P Client"],
  ["FrostWire", "frostwire.exe", "FrostWire Torrent & Media Downloader"],
  ["Ares Galaxy", "ares.exe", "Ares Galaxy P2P Sharing"],
  ["SoulseekQt", "soulseekqt.exe", "Soulseek Music Sharing Network"],
  ["Nicotine+", "nicotine.exe", "Nicotine+ Soulseek Network Client"],
  ["WebTorrent Desktop", "webtorrent.exe", "WebTorrent Streaming Desktop App"]
];

const gamblingAndCheats = [
  ["PokerStars", "pokerstars.exe", "PokerStars Real Money & Play Poker"],
  ["PokerStars Update", "pokerstarsupdate.exe", "PokerStars Client Updater"],
  ["888poker", "888poker.exe", "888poker Online Poker Client"],
  ["888casino", "888casino.exe", "888casino Slots & Live Casino"],
  ["PartyPoker", "partypoker.exe", "PartyPoker Desktop Poker Client"],
  ["GGPoker", "ggpoker.exe", "GGPoker World Series of Poker Client"],
  ["GGPoker Loader", "ggnet.exe", "GGPoker Game Engine"],
  ["WSOP Real Money Poker", "wsop.exe", "World Series of Poker Client"],
  ["Bovada Poker", "bovada.exe", "Bovada Sports & Casino Client"],
  ["BetOnline", "betonline.exe", "BetOnline Sportsbook & Poker"],
  ["Bet365 Desktop", "bet365.exe", "Bet365 Sports Betting & Casino"],
  ["Unibet Poker", "unibetpoker.exe", "Unibet Poker Desktop Client"],
  ["Ignition Casino & Poker", "ignitioncasino.exe", "Ignition Poker & Casino"],
  ["Americas Cardroom", "americascardroom.exe", "ACR Poker Desktop Client"],
  ["Black Chip Poker", "blackchippoker.exe", "Winning Poker Network Client"],
  ["Stake Casino Desktop", "stake.exe", "Stake Crypto Casino & Sportsbook"],
  ["DraftKings Sportsbook", "draftkings.exe", "DraftKings Fantasy & Betting"],
  ["FanDuel Sportsbook", "fanduel.exe", "FanDuel Fantasy & Casino"],
  ["Slotomania", "slotomania.exe", "Slotomania Free Casino Slots"],
  ["Jackpot Party Casino", "jackpotparty.exe", "Jackpot Party Social Slots"],
  ["Heart of Vegas", "heartofvegas.exe", "Heart of Vegas Slots App"],
  ["Big Fish Casino", "bigfishcasino.exe", "Big Fish Social Casino Games"],
  ["DoubleDown Casino", "doubledowncasino.exe", "DoubleDown Interactive Slots"],
  ["Zynga Poker", "zyngapoker.exe", "Zynga Texas Holdem Poker"],
  ["WorldWinner Games", "worldwinner.exe", "WorldWinner Cash Game Tournaments"],

  // Cheats, Trainers & Game Modding Time Wasters
  ["Cheat Engine", "cheatengine-x86_64.exe", "Memory Scanner & Game Cheating Engine"],
  ["Cheat Engine 32", "cheatengine-i386.exe", "Cheat Engine 32-bit Core"],
  ["WeMod Trainer", "wemod.exe", "WeMod All-in-One PC Game Trainer"],
  ["WeMod Auxiliary", "wemodauxiliary.exe", "WeMod Background Game Hook"],
  ["FLiNG Trainer", "flingtrainer.exe", "FLiNG Standalone Game Trainers"],
  ["ArtMoney", "artmoney.exe", "ArtMoney Memory Editor & Hex Tool"],
  ["SpeedHack Tool", "speedhack.exe", "Game Speed Acceleration Utility"],
  ["Vortex Mod Manager", "vortex.exe", "Nexus Mods Vortex Mod Manager"],
  ["Mod Organizer 2", "modorganizer.exe", "Mod Organizer 2 Game Modding"],
  ["Nexus Mod Manager", "nexusclient.exe", "Nexus Mod Manager Community Edition"],
  ["Wallpaper Engine 32", "wallpaper32.exe", "Wallpaper Engine Live Wallpapers"],
  ["Wallpaper Engine 64", "wallpaper64.exe", "Wallpaper Engine Live Wallpapers Background"],
  ["Wallpaper Engine UI", "wallpaperengine.exe", "Wallpaper Engine UI & Browser"],
  ["Lively Wallpaper", "lively.exe", "Lively Animated Desktop Wallpapers"],
  ["VoiceMod Voice Changer", "voicemod.exe", "Voicemod Real-Time Voice Changer & Soundboard"],
  ["Clownfish Voice Changer", "clownfish.exe", "Clownfish Voice Changer for Games"],
  ["Soundpad", "soundpad.exe", "Soundpad Media Player for Voice Chat"],
  ["OBS Studio (Distraction Streaming)", "obs64.exe", "Open Broadcaster Software Studio"],
  ["Streamlabs Desktop", "streamlabs desktop.exe", "Streamlabs Live Broadcasting"],
  ["Action! Screen Recorder", "action.exe", "Mirillis Action! Game Recorder"],
  ["Bandicam Game Recorder", "bdcam.exe", "Bandicam Screen & Game Recording"],
  ["Fraps Game FPS", "fraps.exe", "Fraps Game Capture & Benchmarking"]
];

const casual = [
  ["Microsoft Solitaire Collection", "solitaire.exe", "Microsoft Casual Solitaire"],
  ["Spider Solitaire", "spider.exe", "Windows Spider Solitaire"],
  ["FreeCell", "freecell.exe", "Windows FreeCell Card Game"],
  ["Hearts Card Game", "mshearts.exe", "Microsoft Hearts Card Game"],
  ["Minesweeper", "minesweeper.exe", "Microsoft Minesweeper Puzzle"],
  ["Mahjong Titans", "mahjong.exe", "Windows Mahjong Tile Matching"],
  ["Purble Place", "purbleplace.exe", "Microsoft Windows Casual Kids Game"],
  ["Chess Titans", "chess.exe", "Windows 3D Chess Game"],
  ["Pinball 3D Space Cadet", "pinball.exe", "3D Pinball Space Cadet"],
  ["Candy Crush Saga", "candycrushsaga.exe", "King Candy Crush Match-3"],
  ["Candy Crush Soda Saga", "candycrushsodasaga.exe", "Candy Crush Soda Saga"],
  ["Candy Crush Friends", "candycrushfriendssaga.exe", "Candy Crush Friends"],
  ["Farm Heroes Saga", "farmheroessaga.exe", "King Farm Heroes Match-3"],
  ["Pet Rescue Saga", "petrescuesaga.exe", "King Pet Rescue Puzzle"],
  ["Bubble Witch 3 Saga", "bubblewitch3saga.exe", "King Bubble Witch 3 Saga"],
  ["Subway Surfers", "subwaysurfers.exe", "SYBO Subway Surfers Endless Runner"],
  ["Temple Run 2", "templerun2.exe", "Imangi Temple Run 2"],
  ["Angry Birds 2", "angrybirds2.exe", "Rovio Angry Birds 2"],
  ["Angry Birds Classic", "angrybirds.exe", "Rovio Angry Birds Original"],
  ["Angry Birds Space", "angrybirdsspace.exe", "Rovio Angry Birds Space"],
  ["Plants vs Zombies", "plantsvszombies.exe", "PopCap Plants vs Zombies"],
  ["Plants vs Zombies Garden Warfare", "pvzgw2.exe", "PvZ Garden Warfare 2"],
  ["Bejeweled 3", "bejeweled3.exe", "PopCap Bejeweled 3"],
  ["Peggle Deluxe", "peggle.exe", "PopCap Peggle Deluxe"],
  ["Peggle Nights", "pegglenights.exe", "PopCap Peggle Nights"],
  ["Zuma Deluxe", "zuma.exe", "PopCap Zuma Marble Shooter"],
  ["Zuma's Revenge", "zumasrevenge.exe", "PopCap Zuma's Revenge"],
  ["Feeding Frenzy 2", "feedingfrenzy2.exe", "PopCap Feeding Frenzy 2"],
  ["Chuzzle Deluxe", "chuzzle.exe", "PopCap Chuzzle Match-3"],
  ["Insaniquarium Deluxe", "insaniquariumdeluxe.exe", "PopCap Aquarium Clicker Game"],
  ["Bookworm Adventures", "bookwormadventures.exe", "PopCap Bookworm Adventures"],
  ["Cut the Rope", "cuttherope.exe", "ZeptoLab Cut the Rope Puzzle"],
  ["Fruit Ninja", "fruitninja.exe", "Halfbrick Fruit Ninja Slicing"],
  ["Crossy Road", "crossyroad.exe", "Hipster Whale Crossy Road"],
  ["Jetpack Joyride", "jetpackjoyride.exe", "Halfbrick Jetpack Joyride"],
  ["Flappy Bird PC", "flappybird.exe", "Flappy Bird Arcade"],
  ["Bad Piggies", "badpiggies.exe", "Rovio Bad Piggies Vehicle Construction"],
  ["Asphalt 9 Legends", "asphalt9.exe", "Gameloft Asphalt 9 Legends Arcade Racing"],
  ["Asphalt 8 Airborne", "asphalt8.exe", "Gameloft Asphalt 8 Arcade Racing"],
  ["Minion Rush", "minionrush.exe", "Gameloft Despicable Me Minion Runner"],
  ["Sonic Dash", "sonicdash.exe", "SEGA Sonic Dash Endless Runner"],
  ["Pac-Man Championship Edition", "pacman_ce.exe", "Bandai Namco PAC-MAN"],
  ["Tetris Effect Connected", "tetriseffect.exe", "Enhance Tetris Effect Connected"],
  ["Puyo Puyo Tetris", "puyopuyotetris.exe", "SEGA Puyo Puyo Tetris"],
  ["Uno PC Game", "uno.exe", "Ubisoft UNO Card Game"],
  ["Monopoly Plus", "monopolyplus.exe", "Ubisoft 3D Monopoly Board Game"],
  ["Game of Life 2", "thegameoflife2.exe", "Marmalade Game of Life 2 Board Game"],
  ["Clue / Cluedo", "cluedo.exe", "Classic Mystery Board Game"],
  ["Battleship PC", "battleship.exe", "Ubisoft Battleship Naval Combat"],
  ["Risk Global Domination", "risk.exe", "SMG Studio RISK Strategy Board Game"],
  ["Plague Inc Evolved", "plagueincevolved.exe", "Ndemic Creations Plague Inc."],
  ["Rebel Inc Escalation", "rebelincescalation.exe", "Ndemic Creations Rebel Inc."],
  ["Townscaper", "townscaper.exe", "Oskar Stalberg Townscaper Toy Building"],
  ["Unpacking", "unpacking.exe", "Witch Beam Relaxing Puzzle Game"],
  ["A Little to the Left", "alittletotheleft.exe", "Secret Mode Tidy Puzzle Game"],
  ["Dorfromantik", "dorfromantik.exe", "Toukana Dorfromantik Peaceful Hex Tile Game"],
  ["Mini Metro", "minimetro.exe", "Dinosaur Polo Club Mini Metro"],
  ["Mini Motorways", "minimotorways.exe", "Dinosaur Polo Club Mini Motorways"],
  ["Hidden Folks", "hiddenfolks.exe", "Adriaan de Jongh Hidden Folks Finding Game"],
  ["Cats Hidden in Paris", "catshiddeninparis.exe", "Hidden Cats Finding Game"],
  ["Donut County", "donutcounty.exe", "Ben Esposito Donut County Hole Game"],
  ["Untitled Goose Game", "untitledgoosegame.exe", "House House Untitled Goose Game"],
  ["Goat Simulator 3", "goatsimulator3.exe", "Coffee Stain Goat Simulator 3"],
  ["Goat Simulator", "goatsimulator.exe", "Coffee Stain Original Goat Simulator"],
  ["I Am Bread", "iambread.exe", "Bossa Studios I Am Bread Physics"],
  ["Surgeon Simulator", "surgeonsimulator2013.exe", "Bossa Studios Surgeon Simulator"]
];

// Expand list with variants, 32-bit / 64-bit binaries, and additional games & apps to reach 550+
const extraGames = [
  ["Grand Theft Auto IV", "gtaiv.exe", "GTA IV"],
  ["Grand Theft Auto EFLC", "eflc.exe", "GTA Episodes from Liberty City"],
  ["Max Payne 3", "maxpayne3.exe", "Rockstar Max Payne 3"],
  ["L.A. Noire", "lanoire.exe", "Rockstar L.A. Noire"],
  ["Bully Scholarship Edition", "bully.exe", "Rockstar Bully"],
  ["Mafia Definitive Edition", "mafiadefinitiveedition.exe", "2K Mafia: DE"],
  ["Mafia II", "mafia2.exe", "2K Mafia II"],
  ["Mafia III", "mafia3.exe", "2K Mafia III"],
  ["Assassin's Creed Mirage", "acmirage.exe", "Ubisoft Assassin's Creed Mirage"],
  ["Assassin's Creed Valhalla", "acvalhalla.exe", "Ubisoft AC Valhalla"],
  ["Assassin's Creed Odyssey", "acodyssey.exe", "Ubisoft AC Odyssey"],
  ["Assassin's Creed Origins", "acorigins.exe", "Ubisoft AC Origins"],
  ["Assassin's Creed Syndicate", "acs.exe", "Ubisoft AC Syndicate"],
  ["Assassin's Creed Unity", "acunity.exe", "Ubisoft AC Unity"],
  ["Assassin's Creed Black Flag", "ac4bfsp.exe", "Ubisoft AC IV Black Flag"],
  ["Far Cry 6", "farcry6.exe", "Ubisoft Far Cry 6"],
  ["Far Cry 5", "farcry5.exe", "Ubisoft Far Cry 5"],
  ["Far Cry 4", "farcry4.exe", "Ubisoft Far Cry 4"],
  ["Far Cry 3", "farcry3_d3d11.exe", "Ubisoft Far Cry 3"],
  ["Watch Dogs Legion", "watchdogslegion.exe", "Ubisoft Watch Dogs Legion"],
  ["Watch Dogs 2", "watchdogs2.exe", "Ubisoft Watch Dogs 2"],
  ["Watch Dogs", "watch_dogs.exe", "Ubisoft Watch Dogs"],
  ["Tom Clancy's The Division 2", "thedivision2.exe", "Ubisoft The Division 2"],
  ["Tom Clancy's Ghost Recon Breakpoint", "grb.exe", "Ghost Recon Breakpoint"],
  ["Tom Clancy's Ghost Recon Wildlands", "grw.exe", "Ghost Recon Wildlands"],
  ["For Honor", "forhonor.exe", "Ubisoft For Honor"],
  ["Skull and Bones", "skullandbones.exe", "Ubisoft Skull and Bones"],
  ["Star Wars Jedi Survivor", "jedisurvivor.exe", "EA Star Wars Jedi: Survivor"],
  ["Star Wars Jedi Fallen Order", "starwarsjedifallenorder.exe", "Jedi Fallen Order"],
  ["Star Wars Battlefront II", "starwarsbattlefrontii.exe", "EA Battlefront II"],
  ["Star Wars Squadrons", "starwarssquadrons.exe", "EA Star Wars Squadrons"],
  ["Dead Island 2", "deadisland-win64-shipping.exe", "Deep Silver Dead Island 2"],
  ["Dying Light 2", "dyinglightgame_x64_rwdi.exe", "Techland Dying Light 2"],
  ["Dying Light", "dyinglightgame.exe", "Techland Dying Light"],
  ["Metro Exodus", "metroexodus.exe", "4A Games Metro Exodus"],
  ["Metro Last Light", "metrolastlight.exe", "4A Games Metro Last Light"],
  ["Metro 2033 Redux", "metro2033redux.exe", "4A Games Metro 2033"],
  ["S.T.A.L.K.E.R. 2 Heart of Chornobyl", "stalker2-win64-shipping.exe", "GSC Game World STALKER 2"],
  ["S.T.A.L.K.E.R. Shadow of Chernobyl", "xr_3da.exe", "STALKER Classic X-Ray"],
  ["Control", "control.exe", "Remedy Control"],
  ["Control DX12", "control_dx12.exe", "Remedy Control DirectX 12"],
  ["Alan Wake 2", "alanwake2.exe", "Remedy Alan Wake 2"],
  ["Alan Wake Remastered", "alanwakeremastered.exe", "Alan Wake Remastered"],
  ["Quantum Break", "quantumbreak.exe", "Remedy Quantum Break"],
  ["Quantum Break DX11", "quantumbreak_dx11.exe", "Quantum Break DX11"],
  ["Borderlands 3", "borderlands3.exe", "Gearbox Borderlands 3"],
  ["Borderlands 2", "borderlands2.exe", "Gearbox Borderlands 2"],
  ["Borderlands Pre-Sequel", "borderlandspresequel.exe", "Borderlands Pre-Sequel"],
  ["Tiny Tina's Wonderlands", "wonderlands.exe", "Tiny Tina's Wonderlands"],
  ["BioShock Infinite", "bioshockinfinite.exe", "2K BioShock Infinite"],
  ["BioShock Remastered", "bioshock.exe", "2K BioShock Remastered"],
  ["BioShock 2 Remastered", "bioshock2.exe", "2K BioShock 2 Remastered"],
  ["Prey", "prey.exe", "Arkane Studios Prey"],
  ["Dishonored 2", "dishonored2.exe", "Arkane Studios Dishonored 2"],
  ["Dishonored", "dishonored.exe", "Arkane Studios Dishonored"],
  ["Deathloop", "deathloop.exe", "Arkane Studios Deathloop"],
  ["Hitman World of Assassination", "hitman3.exe", "IO Interactive Hitman 3"],
  ["Hitman 2", "hitman2.exe", "IO Interactive Hitman 2"],
  ["Hitman Absolution", "hma.exe", "IO Interactive Hitman Absolution"],
  ["Just Cause 4", "justcause4.exe", "Square Enix Just Cause 4"],
  ["Just Cause 3", "justcause3.exe", "Square Enix Just Cause 3"],
  ["Sleeping Dogs", "sdhdship.exe", "Square Enix Sleeping Dogs: Definitive Edition"],
  ["Tomb Raider", "tombraider.exe", "Crystal Dynamics Tomb Raider"],
  ["Rise of the Tomb Raider", "rottr.exe", "Rise of the Tomb Raider"],
  ["Shadow of the Tomb Raider", "sottr.exe", "Shadow of the Tomb Raider"],
  ["Deus Ex Mankind Divided", "dxmd.exe", "Eidos Deus Ex: Mankind Divided"],
  ["Deus Ex Human Revolution", "dxhr.exe", "Deus Ex: Human Revolution"],
  ["Batman Arkham Knight", "batmanak.exe", "Rocksteady Batman: Arkham Knight"],
  ["Batman Arkham City", "batmanac.exe", "Batman: Arkham City"],
  ["Batman Arkham Asylum", "shippingpc-bmgame.exe", "Batman: Arkham Asylum"],
  ["Gotham Knights", "gothamknights.exe", "WB Gotham Knights"],
  ["Suicide Squad Kill the Justice League", "suicidesquad.exe", "Rocksteady Suicide Squad"],
  ["Middle-earth Shadow of War", "shadowofwar.exe", "Monolith Shadow of War"],
  ["Middle-earth Shadow of Mordor", "shadowofmordor.exe", "Monolith Shadow of Mordor"],
  ["Dragon Age The Veilguard", "dragonagetheveilguard.exe", "BioWare Dragon Age Veilguard"],
  ["Dragon Age Inquisition", "dragonageinquisition.exe", "BioWare Dragon Age Inquisition"],
  ["Mass Effect Legendary Edition", "masseffectlauncher.exe", "BioWare Mass Effect Legendary"],
  ["Mass Effect Andromeda", "masseffectandromeda.exe", "Mass Effect Andromeda"],
  ["Persona 3 Reload", "p3r.exe", "Atlus Persona 3 Reload"],
  ["Persona 5 Royal", "p5r.exe", "Atlus Persona 5 Royal"],
  ["Persona 4 Golden", "p4g.exe", "Atlus Persona 4 Golden"],
  ["Shin Megami Tensei V Vengeance", "smt5v.exe", "Atlus SMT V Vengeance"],
  ["Metaphor ReFantazio", "metaphor.exe", "Atlus Metaphor: ReFantazio"],
  ["Yakuza Like a Dragon", "yakuza_like_a_dragon.exe", "SEGA Yakuza: Like a Dragon"],
  ["Like a Dragon Infinite Wealth", "likeadragoninfinitewealth.exe", "Infinite Wealth"],
  ["Yakuza 0", "yakuza0.exe", "SEGA Yakuza 0"],
  ["Yakuza Kiwami", "yakuzakiwami.exe", "SEGA Yakuza Kiwami"],
  ["Yakuza Kiwami 2", "yakuzakiwami2.exe", "SEGA Yakuza Kiwami 2"],
  ["Judgment", "judgment.exe", "SEGA Judgment Detective Game"],
  ["Lost Judgment", "lostjudgment.exe", "SEGA Lost Judgment"],
  ["Nier Automata", "nierautomata.exe", "Square Enix NieR:Automata"],
  ["Nier Replicant", "nierreplicant.exe", "Square Enix NieR Replicant"],
  ["Final Fantasy VII Remake", "ff7remake_.exe", "Square Enix FF7 Remake Intergrade"],
  ["Final Fantasy XVI", "ffxvi.exe", "Square Enix Final Fantasy XVI"],
  ["Kingdom Hearts III", "kingdomhearts3.exe", "Square Enix Kingdom Hearts III"],
  ["Dragon Quest XI S", "dragonquestxi.exe", "Square Enix Dragon Quest XI"],
  ["Octopath Traveler II", "octopathtraveler2.exe", "Square Enix Octopath Traveler II"],
  ["Tales of Arise", "tales of arise.exe", "Bandai Namco Tales of Arise"],
  ["Scarlet Nexus", "scarletnexus.exe", "Bandai Namco Scarlet Nexus"],
  ["Code Vein", "codevein-win64-shipping.exe", "Bandai Namco Code Vein"],
  ["Tekken 8", "polar-win64-shipping.exe", "Bandai Namco Tekken 8"],
  ["Tekken 7", "tekken7.exe", "Bandai Namco Tekken 7"],
  ["Street Fighter 6", "streetfighter6.exe", "Capcom Street Fighter 6"],
  ["Street Fighter V", "streetfighterv.exe", "Capcom Street Fighter V"],
  ["Mortal Kombat 1", "mk12.exe", "NetherRealm Mortal Kombat 1"],
  ["Mortal Kombat 11", "mk11.exe", "NetherRealm Mortal Kombat 11"],
  ["Mortal Kombat X", "mk10.exe", "NetherRealm Mortal Kombat X"],
  ["Guilty Gear Strive", "ggst-win64-shipping.exe", "Arc System Guilty Gear -Strive-"],
  ["Dragon Ball FighterZ", "dbfighterz.exe", "Bandai Namco Dragon Ball FighterZ"],
  ["Dragon Ball Sparking Zero", "sparkingzero-win64-shipping.exe", "DB Sparking! ZERO"],
  ["Dragon Ball Xenoverse 2", "dbxv2.exe", "Dragon Ball Xenoverse 2"],
  ["Naruto Shippuden Ultimate Ninja Storm 4", "nsuns4.exe", "Naruto Storm 4"],
  ["Warhammer 40k Space Marine 2", "spacemarine2.exe", "Saber Warhammer Space Marine 2"],
  ["Warhammer 40k Darktide", "darktide.exe", "Fatshark Warhammer 40k Darktide"],
  ["Warhammer Vermintide 2", "vermintide2.exe", "Fatshark Warhammer: Vermintide 2"],
  ["Left 4 Dead 2", "left4dead2.exe", "Valve Left 4 Dead 2"],
  ["Left 4 Dead", "left4dead.exe", "Valve Left 4 Dead"],
  ["Team Fortress 2", "hl2.exe", "Valve Team Fortress 2 / Source Engine"],
  ["Portal 2", "portal2.exe", "Valve Portal 2"],
  ["Portal", "portal.exe", "Valve Portal"],
  ["Garry's Mod", "gmod.exe", "Facepunch Garry's Mod"],
  ["Half-Life Alyx", "hlvr.exe", "Valve Half-Life: Alyx VR"],
  ["Black Mesa", "bms.exe", "Crowbar Collective Black Mesa"],
  ["Killing Floor 2", "kfgame.exe", "Tripwire Killing Floor 2"],
  ["Insurgency Sandstorm", "insurgencyclient-win64-shipping.exe", "Insurgency: Sandstorm"],
  ["Squad", "squadgame.exe", "Offworld Industries Squad"],
  ["Hell Let Loose", "hll-win64-shipping.exe", "Team17 Hell Let Loose"],
  ["Arma 3", "arma3_x64.exe", "Bohemia Interactive Arma 3"],
  ["Arma Reforger", "armareforger.exe", "Bohemia Interactive Arma Reforger"],
  ["DayZ", "dayz_x64.exe", "Bohemia Interactive DayZ"],
  ["SCUM", "scum.exe", "Gamepires SCUM Survival"],
  ["Escape from Tarkov", "escapefromtarkov.exe", "Battlestate Escape from Tarkov"],
  ["Escape from Tarkov Arena", "eftarena.exe", "Escape from Tarkov: Arena"],
  ["Arena Breakout Infinite", "abinfinite.exe", "MoreFun Arena Breakout: Infinite"],
  ["The Finals", "discovery.exe", "Embark Studios The Finals"],
  ["XDefiant", "xdefiant.exe", "Ubisoft XDefiant"],
  ["Spectre Divide", "spectredivide-win64-shipping.exe", "Mountaintop Spectre Divide"],
  ["Marvel Rivals", "marvelrivals-win64-shipping.exe", "NetEase Marvel Rivals"],
  ["Smite 2", "smite2.exe", "Hi-Rez Smite 2 MOBA"],
  ["Smite", "smite.exe", "Hi-Rez Smite MOBA"],
  ["Paladins", "paladins.exe", "Hi-Rez Paladins Champion of the Realm"],
  ["Brawlhalla", "brawlhalla.exe", "Blue Mammoth Brawlhalla"],
  ["Multiversus", "multiversus.exe", "WB Games MultiVersus"],
  ["Party Animals", "partyanimals.exe", "Recreate Games Party Animals"],
  ["Pummel Party", "pummelparty.exe", "Rebuilt Games Pummel Party"],
  ["Duck Game", "duckgame.exe", "Adult Swim Duck Game"],
  ["Stick Fight The Game", "stickfight.exe", "Landfall Stick Fight"],
  ["Content Warning", "content warning.exe", "Landfall Content Warning"],
  ["Rounds", "rounds.exe", "Landfall ROUNDS Roguelike"],
  ["Totally Accurate Battle Simulator", "tabs.exe", "Landfall TABS"],
  ["Human Fall Flat", "human.exe", "No Brakes Games Human: Fall Flat"],
  ["Gang Beasts", "gang beasts.exe", "Boneloaf Gang Beasts"],
  ["Golf With Your Friends", "golf with your friends.exe", "Team17 Golf With Your Friends"],
  ["Golf It!", "golf it.exe", "Perfuse Entertainment Golf It!"],
  ["Tabletop Simulator", "tabletopsimulator.exe", "Berserk Tabletop Simulator"],
  ["Jackbox Party Pack 10", "the jackbox party pack 10.exe", "Jackbox Party Pack 10"],
  ["Jackbox Party Pack 9", "the jackbox party pack 9.exe", "Jackbox Party Pack 9"],
  ["Jackbox Party Pack 8", "the jackbox party pack 8.exe", "Jackbox Party Pack 8"],
  ["Jackbox Party Pack 7", "the jackbox party pack 7.exe", "Jackbox Party Pack 7"],
  ["Jackbox Party Pack 6", "the jackbox party pack 6.exe", "Jackbox Party Pack 6"],
  ["Jackbox Party Pack 5", "the jackbox party pack 5.exe", "Jackbox Party Pack 5"],
  ["Jackbox Party Pack 4", "the jackbox party pack 4.exe", "Jackbox Party Pack 4"],
  ["Jackbox Party Pack 3", "the jackbox party pack 3.exe", "Jackbox Party Pack 3"],
  ["Jackbox Party Pack 2", "the jackbox party pack 2.exe", "Jackbox Party Pack 2"],
  ["Jackbox Party Pack", "the jackbox party pack.exe", "Jackbox Party Pack Original"]
];

function buildEntries(list, category) {
  return list.map(([name, exe, reason], idx) => {
    const cleanId = `distract-${category}-${exe.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${idx}`;
    return {
      id: cleanId,
      name,
      executableName: exe.toLowerCase(),
      category,
      enabled: true,
      reason: reason || `Default FocusGuard ${category} distraction rule`
    };
  });
}

const allApps = [
  ...buildEntries(games, "gaming"),
  ...buildEntries(extraGames, "gaming"),
  ...buildEntries(socials, "social"),
  ...buildEntries(streaming, "streaming"),
  ...buildEntries(gamblingAndCheats, "gambling"),
  ...buildEntries(casual, "casual")
];

// Deduplicate by executableName
const seen = new Set();
const uniqueApps = [];
for (const app of allApps) {
  const key = app.executableName.toLowerCase();
  if (seen.has(key)) continue;
  seen.add(key);
  uniqueApps.push(app);
}

console.log(`Generated ${uniqueApps.length} unique distracting applications.`);

const jsonContent = JSON.stringify(uniqueApps, null, 2);

const jsFrontend = `// Generated comprehensive Distracting Apps Database for LifeOS FocusGuard
// Over 500+ curated games, social media apps, streaming platforms, gambling, and time wasters.

export const DISTRACTING_APPS_DATABASE = ${jsonContent};

export const DISTRACTING_APP_CATEGORIES = [
  { id: "ALL", label: "All Shield Rules", count: ${uniqueApps.length} },
  { id: "gaming", label: "PC Games & Launchers", count: ${uniqueApps.filter(x => x.category === 'gaming').length} },
  { id: "social", label: "Social & Messengers", count: ${uniqueApps.filter(x => x.category === 'social').length} },
  { id: "streaming", label: "Streaming & Media", count: ${uniqueApps.filter(x => x.category === 'streaming').length} },
  { id: "gambling", label: "Gambling, Cheats & Mods", count: ${uniqueApps.filter(x => x.category === 'gambling').length} },
  { id: "casual", label: "Casual & Arcade Games", count: ${uniqueApps.filter(x => x.category === 'casual').length} }
];

export function isDistractingExecutable(nameOrPath) {
  if (!nameOrPath) return false;
  const exe = String(nameOrPath).split(/[\\\\/]/).pop().toLowerCase();
  return DISTRACTING_APPS_DATABASE.some(app => app.executableName === exe);
}
`;

const cjsBackend = `// Generated comprehensive Distracting Apps Database for LifeOS FocusGuard (CommonJS)
// Over 500+ curated games, social media apps, streaming platforms, gambling, and time wasters.

const DISTRACTING_APPS_DATABASE = ${jsonContent};

const DISTRACTING_EXE_SET = new Set(DISTRACTING_APPS_DATABASE.map(app => app.executableName.toLowerCase()));

function isDistractingExecutable(nameOrPath) {
  if (!nameOrPath) return false;
  const exe = String(nameOrPath).split(/[\\\\/]/).pop().toLowerCase();
  return DISTRACTING_EXE_SET.has(exe);
}

function getDistractingAppsList() {
  return DISTRACTING_APPS_DATABASE.slice();
}

module.exports = {
  DISTRACTING_APPS_DATABASE,
  DISTRACTING_EXE_SET,
  isDistractingExecutable,
  getDistractingAppsList
};
`;

fs.mkdirSync(path.resolve('src/data'), { recursive: true });
fs.writeFileSync(path.resolve('src/data/distractingAppsDatabase.js'), jsFrontend, 'utf8');
fs.writeFileSync(path.resolve('electron/distractingAppsDatabase.cjs'), cjsBackend, 'utf8');
console.log('Successfully wrote distractingAppsDatabase files.');
